name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the npm/cli repo
    - uses: actions/checkout@v1

      # Installs the specific version of Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

      # Run the installer script
    - run: node . install

      # Run the tests
    - run: node . run tap -- \"test/tap/*.js\" -t600 -Rclassic -c
      env:
        DEPLOY_VERSION: testing
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_OPTIONAL_TOKEN }}

      # Run the linter
    - run: npx standard

      # Validate licenses
    - run: node . run licenses
