name: PR diff checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - release-next
      - latest
  # pull_request_target:
  #   types:
  #     - opened
  #     - edited
  #     - synchronize

jobs:
  pr-title-format:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.NPM_ROBOT_TOKEN }}
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v3.4.0
        with:
          token: ${{ secrets.NPM_ROBOT_TOKEN }}