name: PR Validation Checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - release-next
      - latest
  # pull_request_target:
  #   types:
  #     - opened
  #     - edited
  #     - synchronize

jobs:
  pr-title-format:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clean-working-dir:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          npm install
      - name: Check for diff
        run: |
          touch lib/utils/config/definitions
          npm run postsnap
          make prune