name: Security Checks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - "**" # globstar means this security check is ran on all branches associated with pull requests

jobs:
  build:
    name: Security Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      # Installs packages defined in package.json file so that twly can be properly used.
      - name: Install NPM Packages
        run: npm install
      
      # Dependencies fail an audit if the results include a vulnerability with a level of moderate or higher
      - name: NPM Audit Production Level Moderate
        run: npm audit --production --audit-level=moderate
      
      # Dependencies fail an audit if the results include a vulnerability with a level of critical or higher
      - name: NPM Audit level Critical
        run: npm audit --audit-level=critical
      
      # Runs Twly to determine how "dry" The codebase is
      - name: Run Twly Static Code Analysis Tool
        run: npm run twly
